apiVersion: v1
kind: ConfigMap
metadata:
  name: bird-config-1
  labels:
    app: bird-1
    type: config
data:
  bird.conf: |+
    debug protocols all;

    protocol device {
        scan time 10;
    }

    protocol static {
        ipv4 {};
        route 172.16.10.10/32 via "eth0";
        route 172.17.10.10/32 via "eth0";
        route 172.18.10.10/32 via "eth0";
        route 172.19.10.10/32 via "eth0";
        route 172.20.10.10/32 via "eth0";
        route 172.21.10.10/32 via "eth0";
        route 172.22.10.10/32 via "eth0";
        route 172.23.10.10/32 via "eth0";
        route 172.24.10.10/32 via "eth0";
        route 172.25.10.10/32 via "eth0";
        route 172.26.10.10/32 via "eth0";
        route 172.27.10.10/32 via "eth0";
        route 172.28.10.10/32 via "eth0";
        route 172.29.10.10/32 via "eth0";
        route 172.30.10.10/32 via "eth0";
        route 172.31.10.10/32 via "eth0";
    }

    protocol bgp {
        local as 65010;
        neighbor 172.100.4.150 as 65011;
        ipv4 {
            next hop self;
            import all;
            export all;
        };
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bird-config-2
  labels:
    app: bird-2
    type: config
data:
  bird.conf: |+
    debug protocols all;

    protocol device {
        scan time 10;
    }

    protocol static {
        ipv4 {};
        route 172.16.10.10/32 via "eth0";
        route 172.17.10.10/32 via "eth0";
        route 172.18.10.10/32 via "eth0";
        route 172.19.10.10/32 via "eth0";
        route 172.20.10.10/32 via "eth0";
        route 172.21.10.10/32 via "eth0";
        route 172.22.10.10/32 via "eth0";
        route 172.23.10.10/32 via "eth0";
        route 172.24.10.10/32 via "eth0";
        route 172.25.10.10/32 via "eth0";
        route 172.26.10.10/32 via "eth0";
        route 172.27.10.10/32 via "eth0";
        route 172.28.10.10/32 via "eth0";
        route 172.29.10.10/32 via "eth0";
        route 172.30.10.10/32 via "eth0";
        route 172.31.10.10/32 via "eth0";
    }

    protocol bgp {
        local as 65011;
        neighbor 172.100.4.99 as 65010;
        ipv4 {
            next hop self;
            import all;
            export all;
        };
    }

